version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: groundctl
    main: .
    binary: ground
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/Ravenium22/groundctl/cmd.Version={{.Version}}
      - -X github.com/Ravenium22/groundctl/cmd.Commit={{.Commit}}
      - -X github.com/Ravenium22/groundctl/cmd.Date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "groundctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

nfpms:
  - id: packages
    package_name: groundctl
    homepage: "https://github.com/Ravenium22/groundctl"
    description: "terraform plan for your local developer machine"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
