package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Ravenium22/groundctl/internal/config"
	"github.com/Ravenium22/groundctl/internal/detector"
	"github.com/Ravenium22/groundctl/internal/model"
	"github.com/spf13/cobra"
)

var exportCmd = &cobra.Command{
	Use:   "export",
	Short: "Export environment spec in various formats",
	Long: `Exports the .ground.yaml tool list for use in other contexts.

Supported formats:
  dockerfile   Dockerfile ENV/RUN stanzas for installing tools
  shell        Shell export statements (source-able)
  json         JSON tool list with detected versions`,
	RunE: runExport,
}

var (
	exportFormat string
	exportOutput string
	exportConfig string
)

func init() {
	exportCmd.Flags().StringVarP(&exportFormat, "format", "f", "dockerfile", "Output format: dockerfile, shell, json")
	exportCmd.Flags().StringVarP(&exportOutput, "output", "o", "", "Write to file (default: stdout)")
	exportCmd.Flags().StringVarP(&exportConfig, "config", "c", "", "Path to .ground.yaml")
	rootCmd.AddCommand(exportCmd)
}

func runExport(cmd *cobra.Command, args []string) error {
	configPath := exportConfig
	if configPath == "" {
		configPath = findConfig()
	}
	if configPath == "" {
		configPath = filepath.Join(".", config.DefaultConfigFile)
	}

	cfg, err := config.Load(configPath)
	if err != nil {
		return err
	}

	// Detect current versions for context
	names := make([]string, len(cfg.Tools))
	for i, t := range cfg.Tools {
		names[i] = t.Name
	}
	detected := detector.DetectByNames(names)
	detectedMap := make(map[string]model.DetectedTool)
	for _, d := range detected {
		detectedMap[d.Name] = d
	}

	var output string
	switch exportFormat {
	case "dockerfile", "docker":
		output = exportDockerfile(cfg, detectedMap)
	case "shell", "sh":
		output = exportShell(cfg, detectedMap)
	case "json":
		data, err := json.MarshalIndent(struct {
			Name  string             `json:"name"`
			Tools []model.DetectedTool `json:"tools"`
		}{
			Name:  cfg.Name,
			Tools: detected,
		}, "", "  ")
		if err != nil {
			return err
		}
		output = string(data) + "\n"
	default:
		return fmt.Errorf("unsupported format %q (use: dockerfile, shell, json)", exportFormat)
	}

	if exportOutput != "" {
		if err := os.MkdirAll(filepath.Dir(exportOutput), 0755); err != nil {
			return fmt.Errorf("could not create output directory: %w", err)
		}
		if err := os.WriteFile(exportOutput, []byte(output), 0644); err != nil {
			return fmt.Errorf("could not write export: %w", err)
		}
		fmt.Printf("Export written to %s\n", exportOutput)
	} else {
		fmt.Print(output)
	}

	return nil
}

// dockerToolInstall maps tool names to Dockerfile RUN commands.
var dockerToolInstall = map[string]string{
	"node":           "curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && apt-get install -y nodejs",
	"python":         "apt-get install -y python3 python3-pip",
	"go":             "curl -fsSL https://go.dev/dl/go${VERSION}.linux-amd64.tar.gz | tar -C /usr/local -xzf -",
	"git":            "apt-get install -y git",
	"docker":         "curl -fsSL https://get.docker.com | sh",
	"curl":           "apt-get install -y curl",
	"wget":           "apt-get install -y wget",
	"make":           "apt-get install -y make",
	"java":           "apt-get install -y default-jdk",
	"ruby":           "apt-get install -y ruby-full",
	"kubectl":        "curl -fsSL https://dl.k8s.io/release/stable.txt | xargs -I {} curl -fsSL https://dl.k8s.io/release/{}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl",
	"terraform":      "apt-get install -y gnupg software-properties-common && curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp.gpg && echo 'deb [signed-by=/usr/share/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com jammy main' > /etc/apt/sources.list.d/hashicorp.list && apt-get update && apt-get install -y terraform",
	"gh":             "curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli.gpg && echo 'deb [signed-by=/usr/share/keyrings/githubcli.gpg] https://cli.github.com/packages stable main' > /etc/apt/sources.list.d/github-cli.list && apt-get update && apt-get install -y gh",
}

func exportDockerfile(cfg *model.GroundConfig, detected map[string]model.DetectedTool) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Generated by groundctl from %s\n", cfg.Name))
	b.WriteString("# Add to your Dockerfile\n\n")

	// ENV stanza with version info
	b.WriteString("# Tool versions (from .ground.yaml)\n")
	for _, tool := range cfg.Tools {
		ver := tool.Version
		if d, ok := detected[tool.Name]; ok && d.Found {
			ver = d.Version
		}
		envName := strings.ToUpper(strings.ReplaceAll(tool.Name, "-", "_")) + "_VERSION"
		b.WriteString(fmt.Sprintf("ENV %s=%s\n", envName, ver))
	}

	b.WriteString("\n# Install tools\n")
	for _, tool := range cfg.Tools {
		if cmd, ok := dockerToolInstall[tool.Name]; ok {
			b.WriteString(fmt.Sprintf("RUN %s\n", cmd))
		} else {
			b.WriteString(fmt.Sprintf("# TODO: install %s manually\n", tool.Name))
		}
	}

	return b.String()
}

func exportShell(cfg *model.GroundConfig, detected map[string]model.DetectedTool) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Generated by groundctl from %s\n", cfg.Name))
	b.WriteString("# Source this file: source <(ground export -f shell)\n\n")

	for _, tool := range cfg.Tools {
		envName := "GROUND_" + strings.ToUpper(strings.ReplaceAll(tool.Name, "-", "_")) + "_VERSION"
		constraint := tool.Version
		b.WriteString(fmt.Sprintf("export %s=%q\n", envName, constraint))

		if d, ok := detected[tool.Name]; ok && d.Found {
			actualName := "GROUND_" + strings.ToUpper(strings.ReplaceAll(tool.Name, "-", "_")) + "_ACTUAL"
			b.WriteString(fmt.Sprintf("export %s=%q\n", actualName, d.Version))
		}
	}

	return b.String()
}
