package cmd

import (
	"fmt"
	"path/filepath"

	"github.com/charmbracelet/lipgloss"
	"github.com/groundctl/groundctl/internal/config"
	"github.com/groundctl/groundctl/internal/detector"
	"github.com/groundctl/groundctl/internal/model"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize a .ground.yaml from your current machine",
	Long:  `Scans your machine for installed tools and creates a .ground.yaml file with the detected versions as the team standard.`,
	RunE:  runInit,
}

var (
	initForce bool
	initDir   string
)

func init() {
	initCmd.Flags().BoolVarP(&initForce, "force", "f", false, "Overwrite existing .ground.yaml")
	initCmd.Flags().StringVarP(&initDir, "dir", "d", ".", "Directory to create .ground.yaml in")
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, args []string) error {
	configPath := filepath.Join(initDir, config.DefaultConfigFile)

	if config.Exists(configPath) && !initForce {
		return fmt.Errorf(".ground.yaml already exists. Use --force to overwrite")
	}

	successStyle := lipgloss.NewStyle().Foreground(lipgloss.Color("10")).Bold(true)
	dimStyle := lipgloss.NewStyle().Foreground(lipgloss.Color("8"))

	fmt.Println(dimStyle.Render("Scanning machine for installed tools..."))
	fmt.Println()

	detected := detector.DetectAll()

	var specs []model.ToolSpec
	for _, tool := range detected {
		if !tool.Found {
			continue
		}
		specs = append(specs, model.ToolSpec{
			Name:     tool.Name,
			Version:  ">=" + tool.Version,
			Severity: model.SeverityRequired,
		})
	}

	cfg := &model.GroundConfig{
		Name:        "my-project",
		Description: "Generated by groundctl init",
		Tools:       specs,
	}

	if err := config.Save(configPath, cfg); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	fmt.Printf("%s Created %s with %d tools detected\n",
		successStyle.Render("✓"),
		configPath,
		len(specs),
	)

	for _, s := range specs {
		fmt.Printf("  %s %s %s\n",
			successStyle.Render("•"),
			s.Name,
			dimStyle.Render(s.Version),
		)
	}

	fmt.Println()
	fmt.Println(dimStyle.Render("Edit .ground.yaml to customize version constraints and add more tools."))

	return nil
}
